// imports.js
export { default as JavaScript } from 'pages/PagesJavaScript';
export { default as MarkUp } from 'pages/PagesMark';
export { default as ReactComponent } from 'pages/PagesReact';
export { default as LayoutComponents } from '../Layout';
export { default as ComponentsHome } from 'pages/ComponentsHome';
export { default as NotFound } from 'pages/PagesNotFound';

export { default as Module1JS } from '../JavaScript/Module1/Module1JS';
export { default as TechInterview } from '../JavaScript/Module1/TechInterview/TechInterview';
export { default as Module6JS } from '../JavaScript/Module6/Module6JS';
export { default as HomeWorkJs6 } from '../JavaScript/Module6/HomeWorkJs6';
export { default as Module1 } from '../React/Module1/Module1';
export { default as PaintingList } from '../React/Module1/Paintings/PaintingList';
export { default as Section } from '../React/Module1/Paintings/Section';
export { default as paintingsData } from '../React/Module1/Paintings/PaintingsData.json';
export { default as PageTitle } from '../../components/React/Module1/Stylization/PageTitle';
export { default as upcomingEvents } from '../React/Module1/Stylization/upcoming-events.json';
export { default as EventBoard } from '../../components/React/Module1/Stylization/EventBoard';
export { default as EmotionPageTitle } from '../../components/React/Module1/Emotion/EmotionPageTitle';
export { default as EmotionEventBoard } from '../../components/React/Module1/Emotion/EmotionEventBoard';
export { default as StackOfFiles } from '../React/Module1/Zero/StackOfFiles';
export { default as cars } from '../React/Module1/Zero/list-of-files';
export { default as ListOfComponentsReact2 } from '../React/Module2/Module2React';
export { default as Counter } from '../React/Module2/Counter/Counter';
export { default as RouterComponent } from '../JavaScript/Module5/Router';
export { default as FirstReactComponent } from '../JavaScript/Module5/FirstReactComponent/FirstReactComponent';
export { default as SecondReactComponent } from '../JavaScript/Module5/SecondReactComponent/SecondReactComponent';
export { Container } from '../../components/AppComponents.styled';
export { default as Dropdown } from '../React/Module2/Dropdown/Dropdown';
